from typing import Any, List, Tuple

class Default: ...

DEFAULT: Any

class PasswordCard:
    version: Any
    def __init__(self, keyword_length: int or str, segment_length: int = ..., seed: Any=...) -> None: ...
    def save_png(self, filename: str, font_size: int = ..., background: str = ..., font: str = ..., font_color: str = ...) -> None: ...
    def save_text(self, filename: str) -> None: ...
    def raw(self) -> List[List[str]]: ...
    def get_password(self, keyword: str) -> str: ...
    def __getitem__(self, row_column: Tuple[int or str, int] or int or str) -> str or List[str]: ...
    def __eq__(self, other: PasswordCard) -> bool: ...

def save_card(card: PasswordCard, filename: str) -> None: ...
def load_card(filename: str) -> PasswordCard: ...
